[project]
name = "s-curve"
version = "0.1.0"
author = "syhanjin"
description = "Velocity, Acceleration, and Jerk limits with initial values"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = []
